name: Publish

on:
  release:
    types: [ released ]

jobs:
  publish:
    name: Release build and publish
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Build artifacts
        run: ./gradlew build

      - name: Publish to MavenCentral
        run: |
          ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository \
            --max-workers 1 \
            -Psigning.keyId="${{ secrets.SIGNING_KEY_ID }}" \
            -Psigning.password="${{ secrets.SIGNING_PASSWORD }}" \
            -PossrhUsername="${{ secrets.OSSRH_USERNAME }}" \
            -PossrhPassword="${{ secrets.OSSRH_PASSWORD }}"
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}

